Workflow
NoroffFEU/social-media-client pull request #481
Opened 2024-08-12 16:01 UTC by robfil50219

2024-08-12 16:02 UTC, robfil50219 reviewed
testing

2024-09-13 11:07 UTC, sulenchy commented on coverage/lcov-report/sorter.js
> +    // returns the summary table element
This file and other files in the coverage folder should have been gitignored.

2024-09-13 11:07 UTC, sulenchy commented on cypress/e2e/1-getting-started/todo.cy.js
> +describe('example to-do app', () => {
This is unrelated to this project. Pls, remove it

2024-09-13 11:08 UTC, sulenchy commented on cypress/e2e/2-advanced-examples/actions.cy.js
> +    // https://on.cypress.io/type
Same as this, remove it

2024-09-13 11:08 UTC, sulenchy commented on cypress/e2e/2-advanced-examples/assertions.cy.js
> +      // of explicit assertions within it.
Remove this too

2024-09-13 11:08 UTC, sulenchy commented on cypress/e2e/2-advanced-examples/connectors.cy.js
> +    it('invokes a callback function with the current subject', () => {
Remove it

2024-09-13 11:08 UTC, sulenchy commented on cypress/e2e/2-advanced-examples/cookies.cy.js
> +    cy.clearCookies()
Remove this too

2024-09-13 11:09 UTC, sulenchy commented on cypress/e2e/2-advanced-examples/network_requests.cy.js
> +
All the test in the `2-advanced-examples` should be removed

2024-09-13 11:19 UTC, sulenchy requested changes
Hi @robfil50219,

Thanks for pushing this out. Unfortunately, your delivery does not meet the requirements. Apart from the Prettier and ESLint configuration setup, everything else is missing. In line with the marking criteria, here’s what you missed:

The tests are missing—both the unit and e2e tests.
The README file is missing.
Next steps: You will need to resit this CA. In your resit, please ensure that you address the missing aspects mentioned above.

Feel free to contact me if you have any questions.

Abiodun

2025-04-07 07:25 UTC, closed without merging